baseurl = "http://www.cmpsoares.com"
title = "CMPSOARES"

# TODO: figure out if I can append something to title for META Title with more detail.

theme = "LoveIt"

publishDir = "docs"

languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

enableEmoji = true
enableGitInfo = true

googleanalytics = "UA-137270540-1"
disqusShortname = "cmpsoares"

[params]
    author = "Carlos Soares"
    description = "Carlos Soares' personal website and blog"
    keywords = "carlos, soares, cmpsoares, blog,developer,personal,devops,sre,site reliability,engineer,go,terraform,automation,monitoring,obsevability,analytics,automation,big data,distributed,datahub,microservice,architecture,docker,kafka, elasticsearch,cassandra,python,nodejs,java,innovation,artificial intelligence,cryptocurrencies,blockchain,startup"
    info = "Curious Automation Hacker & Versatile Site Reliability and Big Data Engineer"
    avatarurl = "images/avatar.jpg"
    # footercontent = "Living is learning, one day at a time."
    footercontent = "This project is still being built and designed so don't be surprised if you find some empty pages..."

    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/cmpsoares91/cmpsoares.com/tree/"

    rtl = false

    # Use inverted colors
    inverted = true

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []

[taxonomies]
  series = "series"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 1
    url = "https://www.linkedin.com/in/cmpsoares/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 2
    url = "https://github.com/cmpsoares91/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/cmpsoares/"
[[params.social]]
    name = "StackExchange"
    icon = "fab fa-stack-exchange"
    weight = 4
    url = "https://stackexchange.com/users/3911310/cmpsoares"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@cmpsoares91"
[[params.social]]
    name = "Quora"
    icon = "fab fa-quora"
    weight = 6
    url = "https://www.quora.com/profile/Carlos-Soares-2"
[[params.social]]
    name = "Gitlab"
    icon = "fab fa-gitlab"
    weight = 7
    url = "https://gitlab.com/cmpsoares91/"


[languages]
    [languages.en]
        languagename = "English"

        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "/posts/"

#        [[languages.en.menu.main]]
#        name = "Projects"
#        weight = 3
#        url = "/projects/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "/contact/"